// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gateway

type Account struct {
	ID string `json:"id"`
}

type CreateAccount struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
