// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gateway

type Account struct {
	Email string `json:"email"`
	ID    string `json:"id"`
	Name  string `json:"name"`
}

type CreateAccount struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
