version: "3.7"

services:
  system-tests:
    build:
      context: ..
      dockerfile: system-tests/Dockerfile
    networks:
      - accounts

networks:
  accounts:
    external: true
    name: ${ENVIRONMENT}_accounts
