name: Continuous integration

on: [push]

jobs:
  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production]
    steps:
      - uses: actions/checkout@v1
      - name: Build service images
        run: docker-compose build
        working-directory: environments/${{ matrix.environment }}
      - name: Start service containers
        run: docker-compose up -d
        working-directory: environments/${{ matrix.environment }}
      - name: Install test dependencies
        run: go get -t ./...
        working-directory: acceptance-tests
      - name: Run acceptance tests
        run: go test ./...
        working-directory: acceptance-tests

  system-tests:
    name: System Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [production]
    steps:
      - uses: actions/checkout@v1
      - name: Build service images
        run: docker-compose build
        working-directory: environments/${{ matrix.environment }}
      - name: Start service containers
        run: docker-compose up -d
        working-directory: environments/${{ matrix.environment }}
      - name: Run system tests
        env:
          NETWORK: ${{ matrix.environment }}_default
        run: docker-compose up --exit-code-from system-tests
        working-directory: system-tests

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [services/accounts]
    steps:
      - uses: actions/checkout@v1
      - name: Install test dependencies
        run: go get -t ./...
        working-directory: ${{ matrix.directory }}
      - name: Run unit tests
        run: go test -cover ./...
        working-directory: ${{ matrix.directory }}
